version: "3"

services:
  nodejs-mongodb:
    image: mongo:6.0.8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /var/tmp/docker/nodejs-mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
